// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package datamodel

import (
	"fmt"
	"io"
	"math"
	"sort"

	delegation "github.com/alanshaw/ucantone/ucan/delegation"
	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *ProviderModel) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{164}); err != nil {
		return err
	}

	// t.Proof (delegation.Delegation) (struct)
	if len("proof") > 8192 {
		return xerrors.Errorf("Value in field \"proof\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("proof"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("proof")); err != nil {
		return err
	}

	if err := t.Proof.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Weight (uint64) (uint64)
	if len("weight") > 8192 {
		return xerrors.Errorf("Value in field \"weight\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("weight"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("weight")); err != nil {
		return err
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Weight)); err != nil {
		return err
	}

	// t.Endpoint (string) (string)
	if len("endpoint") > 8192 {
		return xerrors.Errorf("Value in field \"endpoint\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("endpoint"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("endpoint")); err != nil {
		return err
	}

	if len(t.Endpoint) > 8192 {
		return xerrors.Errorf("Value in field t.Endpoint was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Endpoint))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Endpoint)); err != nil {
		return err
	}

	// t.Provider (did.DID) (struct)
	if len("provider") > 8192 {
		return xerrors.Errorf("Value in field \"provider\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("provider"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("provider")); err != nil {
		return err
	}

	if err := t.Provider.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *ProviderModel) UnmarshalCBOR(r io.Reader) (err error) {
	*t = ProviderModel{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("ProviderModel: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 8)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Proof (delegation.Delegation) (struct)
		case "proof":

			{

				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}
					t.Proof = new(delegation.Delegation)
					if err := t.Proof.UnmarshalCBOR(cr); err != nil {
						return xerrors.Errorf("unmarshaling t.Proof pointer: %w", err)
					}
				}

			}
			// t.Weight (uint64) (uint64)
		case "weight":

			{

				maj, extra, err = cr.ReadHeader()
				if err != nil {
					return err
				}
				if maj != cbg.MajUnsignedInt {
					return fmt.Errorf("wrong type for uint64 field")
				}
				t.Weight = uint64(extra)

			}
			// t.Endpoint (string) (string)
		case "endpoint":

			{
				sval, err := cbg.ReadStringWithMax(cr, 8192)
				if err != nil {
					return err
				}

				t.Endpoint = string(sval)
			}
			// t.Provider (did.DID) (struct)
		case "provider":

			{

				if err := t.Provider.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Provider: %w", err)
				}

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
